name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs: 
  # build: 
  # deploy:      //build and deploy will  run  in parallele

# here the deploy depends on build, wait until build end then run deploy
  # build: 
  # deploy: 
  #   needs: build 
    
  build: 
    env: 
      CI: true  #the create react app test script will know that we are runing in ci env then will disable watch mode
      #PORT: 9800 # we can add port... 
    strategy: #to run our jobs in differnet envir
      matrix: 
        node-version: [14.x, 16.x] #we will create 2 build jobs run in // each run through all steps below
    runs-on: Ubuntu-latest  #or windows-latest #the os and platform will building our prjt on 
    steps:   #steps and actions that are going to be taken by ubuntu while building , steps = scripts
      - uses: actions/checkout@v2   #premade actions from github or third parties
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2  #setup node premade action
        with: #specific version of node
          # node-version: "16"
          node-version: ${{ matrix.node-version }} #passing node verion as a variable
      - run: npm install  #run our own command. to install our dependencies. here will run this scripts : "install": "npm run install-server && npm run install-client",
      - run: npm run build --prefix client
      - run: npm test  # run the command "test": "npm test --prefix server && npm test --prefix client"
                       #but the test in client is in the watch mode so always we should ctrl+q to exit the bash